version: '{build}'
skip_tags: true
image: Visual Studio 2022
build_script:
  - pwsh: ./Build.ps1
test: off
artifacts:
  - path: artifacts/Seq.*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: yA6yDHx8xQNbvvX+L4Aqc1yVcd77wEzrgeEsqF+UaBQqMXdvhJT236wEUX2voTjq
    skip_symbols: true
    artifact: /Seq.*\.nupkg/
    on:
      branch: /^(main|dev)$/
  - provider: GitHub
    auth_token:
      secure: hX+cZmW+9BCXy7vyH8myWsYdtQHyzzil9K5yvjJv7dK9XmyrGYYDj/DPzMqsXSjo
    artifact: /Seq.*\.nupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: main
