<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Shared infrastructure for Seq apps that integrate with email and similar messaging services.</Description>
    <Authors>Datalust</Authors>
    <PackageProjectUrl>https://github.com/datalust/seq-app-mail</PackageProjectUrl>
    <PackageIcon>seq-mail.png</PackageIcon>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/datalust/seq-app-mail</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="Seq.Mail.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="mailkit" Version="4.17.0" />
    <PackageReference Include="Seq.Apps" Version="2023.4.0" />
    <PackageReference Include="Seq.Syntax" Version="2.0.0-dev-00098" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../asset/seq-mail.png" Pack="true" Visible="false" PackagePath="" />
    <EmbeddedResource Include="./Resources/DefaultHtmlBodyTemplate.html" LogicalName="DefaultHtmlBodyTemplate" />
    <EmbeddedResource Include="./Resources/DefaultTextBodyTemplate.txt" LogicalName="DefaultTextBodyTemplate" />
  </ItemGroup>
</Project>
